### PR TITLE
Manage ZFS YUM repo and RPM GPG key

### LINKED ISSUE #8: Manage ZFS Yum repos directly
Using my Yum module with repo purging enabled, unless you define the `yumrepo` resources, it will purge away the ZFS repos.

### PR DESCRIPTION
**Pull request by runejuhl**
Fixes https://github.com/bodgit/puppet-zfs/issues/8

### CODE REVIEW

**Comment by runejuhl** [comment]
Hi @bodgit!
Not quite sure why the CI pipeline fails -- looks like it's got nothing to do with the code I've changed. Anything I can do to fix it?

**Comment by bodgit** [comment]
> Not quite sure why the CI pipeline fails -- looks like it's got nothing to do with the code I've changed.

No, I'm not sure either. They only seem to fail when Travis runs them, I can't reproduce it locally, changing the rspec output so I can see which specific test is failing would be my first option.

A few points on the PR:

- I would prefer to manage the GPG key as a straight `file` resource here.
- Also, I would prefer to manage the Yum repositories using the `yumrepo` type, a lot of the complexity with the `augeas` type can then be removed as it's just flipping the `enabled` attribute on the DKMS or kmod repositories.
- ~~This whole section can be wrapped with a `Boolean $manage_repo = true` parameter so if someone wants to manage the repositories themselves they can do that.~~ (forgot that already existed)
- Using `$facts['os']['release']['full']` will be correct on Red Hat but on CentOS the release will be something like `7.6.1810` and so that `.1810` will likely need to be chopped off for the repository URL's. I would prefer to keep using the old-style facts for now just ot be consistent with the rest of the module. At some point I will convert everything over to using `$facts[...]`.

**Comment by runejuhl** [comment]
Pushed a few changes:

+ gpg keys managed using file resource
+ repos managed using yumrepo
+ fixed the OS release name

Let me know if you have anything else I can do to make it better.

**Comment by bodgit** [comment]
I've merged in your PR with a few changes, I've dropped the testing/source repos as there's no equivalent on Debian/Ubuntu. I'm going to try and get #18 working at least before I cut a new release.

Thanks for the contribution!

**Comment by runejuhl** [comment]
You're more than welcome @bodgit -- thank you for your Puppet modules!

**Comment by bodgit** [comment]
v2.2.5 should be up on the forge now.

**Pull request merged**
